server:
  port: 9000
spring:
  application:
    name: bank-kotlin-crud
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    username: admin
    url: jdbc:mysql://localhost/banks
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true